version: '3'

networks:
  jenkins:

services:
  jenkins:
    image: jenkins/jenkins:2.346.3-jdk11
    container_name: jenkins
    volumes:
      - ./jenkins:/var/jenkins_home jenkins
    networks:
      - jenkins
    ports:
      - 8080:8080
      - 50000:50000 